# Generated by Django 5.0.3 on 2024-04-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='default_images/perfil.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
