# Generated by Django 5.0.3 on 2024-04-30 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='default_images/perfil.jpg', upload_to='profile_images/'),
        ),
    ]
