# Generated by Django 5.0.3 on 2025-01-11 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postview',
            name='user',
        ),
    ]
